### ISSUE TITLE
Update webhook system

### ISSUE THREAD

**Issue by chikof** [dbotsfun/izumo#24]
![Image](https://github.com/dbotsfun/izumo/assets/95551108/3131d39b-75f4-4123-b2ed-803cf0ecdc3c)

This closes [this](https://github.com/orgs/dbotsfun/projects/4/views/1?pane=issue&itemId=60061239)

**Comment by chikof** [comment]
- What query did you use to get an error btw? 

I also didn't understand the 3rd one. In the 2nd idea you're telling me to get rid of the "selection of events" feature and send it in the payload, right I understand that BUT the 3rd one says pretty much the same **xD**.

**Comment by chikof** [comment]
I also wanted to create a microservice for the webhooks feature. I was thinking of sending a request to our webhook microservice and the microservice send a request to their webhook so we don't expose the server IP?

**Comment by simxnet** [comment]
> * What query did you use to get an error btw?
createWebhook mutation

**Comment by simxnet** [comment]
andd with the 3rd one i wanted to say payload instead of events, mb

**Comment by chikof** [comment]
Alright, so I could remove the payload selection feature and leave the events one. I don't want to send requests to the microservice if they're not intended to be sent.

**Comment by simxnet** [comment]
You could send the event type inside the payload so users could manage what to do with it

**Comment by chikof** [comment]
I forgot to close this PR but basically it's done, we have [Yoizuki](https://github.com/dbotsfun/yoizuki) for this.
